(include_subdirs unqualified)

(library
 (name dio_strategies)
 (public_name dio.strategies)
 (libraries
  yojson
  logging
  dio.persistence
  dio.kraken
  dio.hyperliquid
  dio.lighter
  lwt
  lwt.unix
  unix)
 (modules
  Strategy_common
  Suicide_grid
  Suicide_grid_types
  Suicide_grid_config
  Suicide_grid_reservation
  Suicide_grid_orders
  Suicide_grid_execution
  Suicide_grid_events
  Market_maker
  Fee_cache
  Auto_hedger))
