(include_subdirs unqualified)

(library
 (name dio_strategies)
 (public_name dio.strategies)
 (libraries
  yojson
  logging
  dio.persistence
  dio.kraken
  dio.hyperliquid
  dio.lighter
  dio.latency_profiling
  lwt
  lwt.unix
  unix)
 (modules
  Strategy_common
  Jacobs_ladder
  Jacobs_ladder_types
  Strategy_state
  Jacobs_ladder_config
  Jacobs_ladder_reservation
  Jacobs_ladder_orders
  Strategy_sell_orders
  Jacobs_ladder_execution
  Jacobs_ladder_events
  Fee_cache
  Strategy_actions
  Strategy_actions_builtin
  Account_state
  Strategy_actions_trade
  Strategy_engine
  Strategy_actions_grid
  Strategy_expr
  Strategy_file
  Strategy_compile
  Strategy_guard
  Strategy_runtime
  Strategy_trace
  Strategy_event_recorder
  Strategy_equivalence
  Exchange_capabilities
  Platform_accounting
  Strategy_cli))
