(* Oracle_core - the pure decision core of the capital oracle.

   One source of truth for every quantity the oracle emits, straight from
   the spec:

   - price history references: worst peak-to-trough decline (recovery
     irrelevant), ATH and ATL over the full all-time merged series.
   - runway math: realized_dd, runway_pct = mdd * target_survival,
     floor_price, remaining_drop - resolved into one of three regimes
     (Normal / Floor extension / Unprecedented lows).
   - aggressiveness = realized_dd / mdd, biasing parameter selection toward
     accumulation at cheap prices without ever overriding survival or bounds.
   - survival: a candidate (grid_interval, buy_qty) walks the geometric
     ladder down through the funded depth (current -> funding floor); d_surv
     is the fraction of that depth survived before quote would be exhausted.
     d_surv >= 1.0 meets the target_survival requirement. Buy-side fees are
     charged per fill; fee-in-base venues receive fee-deducted base.
   - parameter search within hardened bounds (buy_qty in [qty, qty *
     qty_cap_mult], grid_interval in [gi_min, gi_max]) with the three
     branches Unreachable / Reachable / Surplus, evaluated in order.
   - the four-field decision record {active; grid_interval; buy_qty;
     sell_qty} - raw floats, generated by exactly one code path here.

   Everything is pure and in-memory: no network, no clocks, no logging. The
   caller (oracle_runtime / dio-oracle.exe) supplies live price, balances
   and config bounds. *)

(* ------------------------------------------------------------------ *)
(* Price-history references                                           *)
(* ------------------------------------------------------------------ *)

(** Reference quantities derived from an asset's full all-time series. *)
type references =
  { max_drawdown_pct : float
    (** Single worst peak-to-trough percentage decline (0..1); recovery is
        irrelevant - an unrecovered collapse counts at full depth. Measured
        from the running peak of closes to the deepest subsequent low. *)
  ; ath : float (** All-time high price (intrabar high). *)
  ; atl : float (** All-time low price (intrabar low). *)
  }

let references_of ~(bars : Oracle_types.bar array) : references option =
  let n = Array.length bars in
  if n = 0
  then None
  else (
    let peak_close = ref 0.0 in
    let best_dd = ref 0.0 in
    let ath = ref 0.0 in
    let atl = ref Float.infinity in
    Array.iter
      (fun (b : Oracle_types.bar) ->
         let valid_close = Float.is_finite b.close && b.close > 0.0 in
         let valid_low = Float.is_finite b.low && b.low > 0.0 in
         if valid_low then atl := Float.min !atl b.low;
         if Float.is_finite b.high && b.high > 0.0 then ath := Float.max !ath b.high;
         if valid_close && valid_low
         then (
           if b.close > !peak_close then peak_close := b.close;
           (* Trough measured against the running close-peak: each bar's own
              low competes immediately against the highest close so far. *)
           if !peak_close > 0.0
           then best_dd := Float.max !best_dd (1.0 -. (b.low /. !peak_close))))
      bars;
    if Float.is_infinite !atl then atl := 0.0;
    if !ath = 0.0
    then None
    else Some { max_drawdown_pct = Float.min 0.999999 !best_dd; ath = !ath; atl = !atl })
;;

(* ------------------------------------------------------------------ *)
(* Runway math                                                        *)
(* ------------------------------------------------------------------ *)

type regime =
  | Normal (** current > floor_price: the grid funds remaining_drop. *)
  | Floor_extension
  (** Living at/below the percentage-derived floor: funding extends down
        to the all-time low price. *)
  | Unprecedented_lows
  (** Living at the deepest drawdown AND at or below ATL: maximum
        conservatism (grid_interval = gi_max, buy_qty = qty). *)

type runway =
  { realized_dd : float (** (ath - current) / ath *)
  ; runway_pct : float (** max_drawdown_pct * target_survival *)
  ; floor_price : float (** ath * (1 - runway_pct) *)
  ; remaining_drop : float (** (current - floor_price) / current *)
  ; funded_floor : float
    (** The price the ladder must survive down to: floor_price (Normal) or
        atl (Floor extension). Meaningless in Unprecedented lows. *)
  ; regime : regime
  ; aggressiveness : float (** realized_dd / max_drawdown_pct clamped 0..1 *)
  }

let runway_of ~(current : float) ~(refs : references) ~(target_survival : float) : runway =
  let ath = refs.ath in
  let realized_dd = Float.max 0.0 (Float.min 1.0 ((ath -. current) /. ath)) in
  let runway_pct = refs.max_drawdown_pct *. target_survival in
  let floor_price = ath *. (1.0 -. runway_pct) in
  let remaining_drop = (current -. floor_price) /. current in
  let regime, funded_floor =
    if current > floor_price
    then Normal, floor_price
    else if
      refs.max_drawdown_pct > 0.0
      && realized_dd >= refs.max_drawdown_pct
      && current <= refs.atl
    then Unprecedented_lows, refs.atl
    else Floor_extension, refs.atl
  in
  let aggressiveness =
    if refs.max_drawdown_pct <= 0.0
    then if realized_dd > 0.0 then 1.0 else 0.0
    else Float.max 0.0 (Float.min 1.0 (realized_dd /. refs.max_drawdown_pct))
  in
  { realized_dd
  ; runway_pct
  ; floor_price
  ; remaining_drop
  ; funded_floor
  ; regime
  ; aggressiveness
  }
;;

(* ------------------------------------------------------------------ *)
(* Survival                                                           *)
(* ------------------------------------------------------------------ *)

(** Per-asset sizing bounds consumed by the search. *)
type bounds =
  { qty : float (** Base order size (search lower bound). *)
  ; qty_cap_mult : float (** Upper bound multiplier: qty * qty_cap_mult. *)
  ; gi_min : float (** Tightest allowed grid interval (%). *)
  ; gi_max : float (** Widest allowed grid interval (%). *)
  }

(** Venue fee model for the survival walk: maker_fee is the quote-side
    fraction charged per fill; [fee_in_base_buy] venues (Kraken-style spot
    buys) deduct the buy fee from the received base instead of the paid
    quote. *)
type fee_model =
  { maker_fee : float
  ; fee_in_base_buy : bool
  }

let default_fees = { maker_fee = 0.0; fee_in_base_buy = false }

(** Fraction 0..1 (>= 1 exactly when the whole depth is funded) of the
    funded depth [current -> funded_floor] the candidate ladder survives
    before its quote runs out. The ladder descends geometrically at [gi]%
    spacing buying [buy_qty] at every rung; each buy costs
    qty*price*(1+maker_fee) in quote (a fee-in-base venue credits
    fee-deducted base, which cannot rescue a pure descent and is therefore
    bookkeeping-only here). Surviving the whole depth returns 1.0 plus the
    leftover quote expressed as a fraction of one further rung's cost, so
    "exceeded with quote left over" (the Surplus branch) is observable as
    d_surv > 1.0. *)
let d_surv_of
      ~(current : float)
      ~(funded_floor : float)
      ~(gi : float)
      ~(buy_qty : float)
      ~(quote : float)
      ~(fees : fee_model)
  : float
  =
  if buy_qty <= 0.0 || gi <= 0.0 || current <= 0.0
  then Float.infinity
  else if current <= funded_floor
  then Float.infinity (* nothing left to fund *)
  else (
    let step = 1.0 -. (gi /. 100.0) in
    let depth = current -. funded_floor in
    let remaining = ref quote in
    let last_price = ref current in
    let funded_whole_depth = ref true in
    let p = ref (current *. step) in
    while !funded_whole_depth && !p >= funded_floor -. 1e-12 do
      let cost = buy_qty *. !p *. (1.0 +. fees.maker_fee) in
      if cost <= !remaining +. 1e-9
      then (
        remaining := !remaining -. cost;
        last_price := !p;
        p := !p *. step)
      else funded_whole_depth := false
    done;
    if !funded_whole_depth
    then
      1.0
      +. Float.min
           1.0
           (!remaining
            /. Float.max 1e-12 (buy_qty *. !last_price *. (1.0 +. fees.maker_fee)))
    else Float.max 0.0 (Float.min 1.0 ((current -. !last_price) /. depth)))
;;

(* ------------------------------------------------------------------ *)
(* Parameter search                                                   *)
(* ------------------------------------------------------------------ *)

type branch =
  | Unreachable (** No candidate meets the funded-depth requirement. *)
  | Reachable (** Target met inside the bounds. *)
  | Surplus (** Most aggressive corner exceeds the target with quote left. *)

type resolution =
  { branch : branch
  ; grid_interval : float
  ; buy_qty : float
  ; d_surv : float (** The emitted candidate's survival fraction. *)
  }

let search_resolution = 24

(** Resolves (grid_interval, buy_qty) within [bounds] for a strategy holding
    [quote] available at live price [current], whose runway requires
    surviving down to [funded_floor]. The spec's three branches are
    evaluated in order:

    1. Unreachable - no candidate reaches target_survival: emit the most
       conservative corner (buy_qty = qty, grid_interval = gi_max).
    2. Surplus - the most aggressive corner (qty * qty_cap_mult, gi_min)
       funds the entire depth with quote left over (d_surv > 1): take it.
    3. Reachable - scan the bounded candidate grid; among survivors pick the
       candidate maximizing the aggressiveness-weighted mix of large size
       and tight spacing (deeper positions accumulate harder; shallow ones
       resolve conservatively). Never overrides survival or bounds.

    Unprecedented lows short-circuits the search into maximum conservatism
    (the same corner Unreachable emits). Branch flips are instant on
    recompute - no hysteresis anywhere. *)
let resolve
      ~(regime : regime)
      ~(current : float)
      ~(funded_floor : float)
      ~(aggressiveness : float)
      ~(bounds : bounds)
      ~(quote : float)
      ~(fees : fee_model)
      ~target_survival:(_ : float)
      ?(resolution = search_resolution)
      ()
  : resolution
  =
  let qty_min = Float.max 1e-12 bounds.qty in
  let qty_max = Float.max qty_min (bounds.qty *. Float.max 1.0 bounds.qty_cap_mult) in
  let gi_lo = Float.min bounds.gi_min bounds.gi_max in
  let gi_hi = Float.max bounds.gi_min bounds.gi_max in
  let ds gi buy_qty = d_surv_of ~current ~funded_floor ~gi ~buy_qty ~quote ~fees in
  let conservative () =
    { branch = Unreachable
    ; grid_interval = gi_hi
    ; buy_qty = qty_min
    ; d_surv = ds gi_hi qty_min
    }
  in
  if regime = Unprecedented_lows
  then conservative ()
  else (
    let corner = ds gi_lo qty_max in
    if corner > 1.0
    then { branch = Surplus; grid_interval = gi_lo; buy_qty = qty_max; d_surv = corner }
    else (
      let n = float_of_int (Int.max 2 resolution) in
      let best
        : (float * float * float * float (* score, buy_qty, gi, d_surv *)) option ref
        =
        ref None
      in
      for i = 0 to resolution - 1 do
        let gi_v = gi_lo +. ((gi_hi -. gi_lo) *. float_of_int i /. (n -. 1.0)) in
        for j = 0 to resolution - 1 do
          let buy_qty =
            qty_min +. ((qty_max -. qty_min) *. float_of_int j /. (n -. 1.0))
          in
          let dsv = ds gi_v buy_qty in
          if dsv >= 1.0
          then (
            let qty_norm = (buy_qty -. qty_min) /. (qty_max -. qty_min) in
            let tight_norm = (gi_hi -. gi_v) /. Float.max 1e-12 (gi_hi -. gi_lo) in
            let aggressive_score = (qty_norm +. tight_norm) /. 2.0 in
            let conservative_score = 1.0 -. aggressive_score in
            let score =
              (aggressiveness *. aggressive_score)
              +. ((1.0 -. aggressiveness) *. conservative_score)
            in
            let better =
              match !best with
              | None -> true
              | Some (bs, bqty, bgi, _) ->
                if score > bs +. 1e-12
                then true
                else if score < bs -. 1e-12
                then false
                else
                  (* Ties: prefer larger size, then tighter spacing. *)
                  buy_qty > bqty +. 1e-12
                  || (Float.abs (buy_qty -. bqty) <= 1e-12 && gi_v < bgi)
            in
            if better then best := Some (score, buy_qty, gi_v, dsv))
        done
      done;
      match !best with
      | Some (_, buy_qty, gi_v, dsv) ->
        { branch = Reachable; grid_interval = gi_v; buy_qty; d_surv = dsv }
      | None -> conservative ()))
;;

(* ------------------------------------------------------------------ *)
(* Decision record                                                    *)
(* ------------------------------------------------------------------ *)

(** The strategy-facing contract: exactly these four fields, raw floats -
    normalization happens at the exchange layer. Generated only by
    [decision_of]; no second copy exists anywhere in the engine. *)
type decision =
  { active : bool
  ; grid_interval : float
  ; buy_qty : float
  ; sell_qty : float
  }

(** Assembles the decision record from a resolved parameter set.

    Activity follows the spec exactly: active <=> d_surv >=
    min_active_dsurv, subject to affordability (available quote must cover
    buy_qty x current). target_survival drives sizing only - it never gates
    activity here. [sell_qty] passes through from the venue pool accounting
    (base pool minus reserved_base minus resting-sell base). *)
let decision_of
      ~(resolution : resolution)
      ~(sell_qty : float)
      ~(available_quote : float)
      ~(current : float)
      ~(min_active_dsurv : float)
      ?(has_resting_buy = false)
      ()
  : decision
  =
  let affordable =
    has_resting_buy || available_quote >= (resolution.buy_qty *. current) -. 1e-9
  in
  { active = (resolution.d_surv >= min_active_dsurv || has_resting_buy) && affordable
  ; grid_interval = resolution.grid_interval
  ; buy_qty = resolution.buy_qty
  ; sell_qty
  }
;;
