(* Oracle runtime - event-driven capital allocation across venues.

   One pass re-resolves every configured asset: all-time merged price
   history -> references -> runway -> survival-replay parameter search ->
   decision record, sized against per-venue pools walked in CONFIG
   PRESENTATION ORDER (first entry = highest priority; capacity passes down;
   a lower-priority strategy is never starved while quote exists). Pools are
   PER VENUE: one quote pool shared by that venue's strategies, never
   crossing venues.

   The hot path is pure arithmetic over in-process state (<10ms p99):
   - price history lives in a cache refreshed on a background cadence
     ([refresh_seconds] fallback poll);
   - balances come from the websocket-fed live store when present, otherwise
     the last fetched snapshot, adjusted IN PROCESS by fill/cancel deltas
     (notify_fill / notify_order_cancel) so events never wait on network;
   - live prices read the in-process top-of-book with a sane-band check
     against the last bar close.

   Events coalesce into a single re-resolve: fills, cancels, balance
   changes, and explicit requests all just wake the loop; one pass consumes
   everything pending.

   Strategy-facing contract: exactly four values per asset - [active],
   [grid_interval], [buy_qty], [sell_qty] - generated by exactly one code
   path (the pass below) and consumed everywhere. Values are emitted for
   inactive strategies too, for visibility, pool accounting, and immediate
   reactivation eligibility. All normalization happens at the exchange
   layer. Diagnostics ([reason], [d_surv], [regime], [branch]) exist for
   logs and dio-oracle output only. *)

module Exchange = Dio_exchange.Exchange_intf
open Lwt.Infix

let section = "oracle_runtime"

(* ------------------------------------------------------------------ *)
(* Configuration                                                      *)
(* ------------------------------------------------------------------ *)

(** Per-asset overrides keyed by symbol ("oracle"."assets"). Every field is
    optional; absent fields inherit the top-level default. *)
type asset_overrides =
  { target_survival : float option
  ; min_active_dsurv : float option
  ; qty_cap_mult : float option
  }

type runtime_config =
  { target_survival : float
    (** Fraction of the historical max drawdown the ladder's runway covers:
        runway_pct = max_drawdown_pct * target_survival. Drives sizing
        ONLY - it never gates activity. *)
  ; min_active_dsurv : float
    (** Active <=> replayed d_surv >= this, subject to affordability. *)
  ; qty_cap_mult : float
    (** Buy-size upper bound multiplier: buy_qty in [qty, qty * mult]. *)
  ; refresh_seconds : float (** Background fallback poll for history and balances. *)
  ; assets : (string * asset_overrides) list
  }

let default_config () =
  { target_survival = 0.95
  ; min_active_dsurv = 0.0
  ; qty_cap_mult = 1.5
  ; refresh_seconds = 300.0
  ; assets = []
  }
;;

let effective_knobs ~(config : runtime_config) ~(symbol : string) : float * float * float =
  let o =
    List.find_opt (fun (s, _) -> String.equal s symbol) config.assets |> Option.map snd
  in
  let or_default opt default = Option.value opt ~default in
  ( or_default (Option.bind o (fun o -> o.target_survival)) config.target_survival
  , or_default (Option.bind o (fun o -> o.min_active_dsurv)) config.min_active_dsurv
  , or_default (Option.bind o (fun o -> o.qty_cap_mult)) config.qty_cap_mult )
;;

(* ------------------------------------------------------------------ *)
(* Decision record & publish machinery                                *)
(* ------------------------------------------------------------------ *)

(** One asset's live trading decision, published for the domain workers.
    The contract is the four sizing/activity fields; the rest is
    observability. *)
type decision =
  { exchange : string
  ; symbol : string
  ; active : bool (** Run the strategy (place/amend buys); sells always run. *)
  ; reason : string (** Why inactive, when inactive (logs only). *)
  ; grid_interval : float (** Contract: resolved spacing in %. *)
  ; buy_qty : float (** Contract: buy order size in base units. *)
  ; sell_qty : float (** Contract: sell size from the venue base pool. *)
  ; max_drawdown_pct : float (** Historical lifetime peak-to-trough max drawdown. *)
  ; d_surv : float (** Replayed survival fraction (observability). *)
  ; regime : string (** Normal / floor extension / unprecedented lows. *)
  ; branch : string (** Search outcome: reachable / surplus / unreachable. *)
  ; cancel_resting_buys : bool
    (** Cancellation cascade action: a higher-priority strategy needs this
        asset's tied quote; the domain must cancel its resting buys so the
        capital returns to the pool. The resulting cancel event wakes the
        runtime and every cancelled strategy re-evaluates immediately,
        resuming iff quote covers its buy. *)
  ; updated_at : float (** Unix time of the pass that produced this. *)
  }

let decisions_ref : decision list Atomic.t = Atomic.make []

let decisions_map : (string * string, decision) Hashtbl.t Atomic.t =
  Atomic.make (Hashtbl.create 16)
;;

let key_of (d : decision) = d.exchange, d.symbol
let publish_generation : int Atomic.t = Atomic.make 0
let get_publish_generation () = Atomic.get publish_generation
let decisions () = Atomic.get decisions_ref

let decision_for ~(exchange : string) ~(symbol : string) : decision option =
  Hashtbl.find_opt (Atomic.get decisions_map) (exchange, symbol)
;;

let tracks_asset ~(exchange : string) ~(symbol : string) : bool =
  Hashtbl.mem (Atomic.get decisions_map) (exchange, symbol)
;;

let publish ~(on_publish : string list -> decision list -> unit) (fresh : decision list) =
  let prev = Atomic.get decisions_map in
  let next = Hashtbl.copy prev in
  List.iter (fun d -> Hashtbl.replace next (key_of d) d) fresh;
  (* Changed symbols: anything new, removed, or whose activity/sizing moved. *)
  let changed =
    List.filter
      (fun (d : decision) ->
         match Hashtbl.find_opt prev (key_of d) with
         | None -> true
         | Some old ->
           old.active <> d.active
           || Float.abs (old.grid_interval -. d.grid_interval) > 1e-12
           || Float.abs (old.buy_qty -. d.buy_qty) > 1e-12
           || Float.abs (old.sell_qty -. d.sell_qty) > 1e-12)
      fresh
    |> List.map (fun (d : decision) -> d.symbol)
  in
  Atomic.set decisions_ref fresh;
  Atomic.set decisions_map next;
  Atomic.incr publish_generation;
  if changed <> [] then on_publish changed fresh
;;

let pass_count : int Atomic.t = Atomic.make 0

(* ------------------------------------------------------------------ *)
(* Profilers                                                          *)
(* ------------------------------------------------------------------ *)

type engine_profilers =
  { prof_pass : Latency_profiler.t
  ; prof_balance : Latency_profiler.t
  ; prof_fetch : Latency_profiler.t
  }

let engine_profs =
  lazy
    { prof_pass =
        Latency_profiler.create ~bucket_us:1_000 ~max_latency_us:60_000_000 "oracle:pass"
    ; prof_balance =
        Latency_profiler.create
          ~bucket_us:1_000
          ~max_latency_us:60_000_000
          "oracle:balance"
    ; prof_fetch =
        Latency_profiler.create ~bucket_us:1_000 ~max_latency_us:60_000_000 "oracle:fetch"
    }
;;

let span_from t = Mtime.Span.of_uint64_ns (Int64.sub (Mtime_clock.now_ns ()) t)
let asset_profiler_cache : (string, Latency_profiler.t) Hashtbl.t = Hashtbl.create 16
let asset_profiler_mutex = Mutex.create ()

let asset_profiler_of symbol =
  Mutex.lock asset_profiler_mutex;
  let prof =
    match Hashtbl.find_opt asset_profiler_cache symbol with
    | Some p -> p
    | None ->
      let p =
        Latency_profiler.create
          ~bucket_us:1
          ~max_latency_us:100_000
          ("oracle:asset:" ^ symbol)
      in
      Hashtbl.replace asset_profiler_cache symbol p;
      p
  in
  Mutex.unlock asset_profiler_mutex;
  prof
;;

let record_asset_latency symbol span cause =
  Latency_profiler.record_with_cause (asset_profiler_of symbol) span cause
;;

(** Engine-global oracle latency snapshots (most recently completed windows),
    for the dashboard. *)
let profiler_snapshots () =
  if Lazy.is_val engine_profs
  then (
    let p = Lazy.force engine_profs in
    [ "pass", Latency_profiler.published_snapshot p.prof_pass
    ; "balance", Latency_profiler.published_snapshot p.prof_balance
    ; "fetch", Latency_profiler.published_snapshot p.prof_fetch
    ])
  else []
;;

(** Per-asset oracle latency snapshots for the dashboard's per-domain rows. *)
let asset_profiler_snapshots () =
  Mutex.lock asset_profiler_mutex;
  let snaps =
    Hashtbl.fold
      (fun symbol prof acc ->
         (symbol, Latency_profiler.published_snapshot prof) :: acc)
      asset_profiler_cache
      []
  in
  Mutex.unlock asset_profiler_mutex;
  snaps
;;

(* ------------------------------------------------------------------ *)
(* History cache                                                      *)
(* ------------------------------------------------------------------ *)

(** Materialized state: Some epoch once the first history refresh attempt
    finished (success or not) - distinguishes "still loading" from "loaded
    but no decision". *)
type materialized_state = { m_epoch : int }

let materialized_ref : materialized_state option Atomic.t = Atomic.make None
let materialized () = Atomic.get materialized_ref
let refresh_fiber : unit Lwt.t option ref = ref None
let refresh_generation : int Atomic.t = Atomic.make 0
let get_refresh_generation () = Atomic.get refresh_generation
let history_changed : bool Atomic.t = Atomic.make false
let history_cache : (string * string, Oracle_types.series) Hashtbl.t = Hashtbl.create 16

let history_of_cached ~(offline : bool) ~(exchange : string) ~(symbol : string)
  : Oracle_types.series Lwt.t
  =
  match Hashtbl.find_opt history_cache (exchange, symbol) with
  | Some s -> Lwt.return s
  | None -> Oracle_pipeline.history_of ~offline ~exchange ~symbol
;;

let same_bars (a : Oracle_types.bar array) (b : Oracle_types.bar array) =
  Array.length a = Array.length b
  &&
  let rec go i =
    i < 0
    || ((let (x : Oracle_types.bar) = a.(i) in
         let (y : Oracle_types.bar) = b.(i) in
         String.equal x.date y.date
         && Float.abs (x.close -. y.close) <= 1e-12 *. Float.max 1.0 (Float.abs x.close)
         && Float.abs (x.high -. y.high) <= 1e-12 *. Float.max 1.0 (Float.abs x.high)
         && Float.abs (x.low -. y.low) <= 1e-12 *. Float.max 1.0 (Float.abs x.low))
        && go (i - 1))
  in
  go (Array.length a - 1)
;;

(** Refresh one asset's merged all-time history into the cache. Returns
    whether the bars actually changed. Network work - background only. *)
let refresh_asset_history ~(offline : bool) ~(exchange : string) ~(symbol : string)
  : bool Lwt.t
  =
  Lwt.catch
    (fun () ->
       Oracle_pipeline.history_of ~offline ~exchange ~symbol
       >|= fun series ->
       let changed =
         match Hashtbl.find_opt history_cache (exchange, symbol) with
         | Some prev -> not (same_bars prev.bars series.bars)
         | None -> true
       in
       Hashtbl.replace history_cache (exchange, symbol) series;
       changed)
    (fun exn ->
       Logging.warn_f
         ~section
         "history refresh failed for %s/%s: %s"
         exchange
         symbol
         (Printexc.to_string exn);
       Lwt.return false)
;;

let pass_attempts : int Atomic.t = Atomic.make 0
let first_pass_attempt_done () = Atomic.get pass_attempts >= 1
let tracks_any () = Hashtbl.length (Atomic.get decisions_map) > 0

(* ------------------------------------------------------------------ *)
(* Wake / lifecycle                                                   *)
(* ------------------------------------------------------------------ *)

let shutdown_requested = Atomic.make false
let is_stopped () = Atomic.get shutdown_requested
let shutdown () = Atomic.set shutdown_requested true
let pass_requested : int Atomic.t = Atomic.make 0
let wake_condition : unit Lwt_condition.t = Lwt_condition.create ()

let request_pass () =
  Atomic.incr pass_requested;
  Lwt_condition.broadcast wake_condition ()
;;

let pass_requested_changed generation = Atomic.get pass_requested <> generation

(** Sleeps until the deadline OR any wake (pass request, shutdown).
    Register-then-recheck closes the lost-wakeup race: an event landing
    between the predicate check and the wait registration is caught by the
    self-broadcast, since the waiter is registered by then. *)
let rec wait_until ~(deadline : float) ~(generation : int) () =
  if is_stopped () || pass_requested_changed generation
  then Lwt.return_unit
  else (
    let now = Unix.gettimeofday () in
    if now >= deadline
    then Lwt.return_unit
    else (
      let w = Lwt_condition.wait wake_condition in
      if is_stopped () || pass_requested_changed generation
      then Lwt_condition.broadcast wake_condition ();
      Lwt.pick
        [ (w >|= fun () -> ())
        ; (Lwt_unix.sleep (Float.max 0.0 (deadline -. now)) >|= fun () -> ())
        ]
      >>= fun () -> wait_until ~deadline ~generation ()))
;;

(* ------------------------------------------------------------------ *)
(* Price anchors                                                      *)
(* ------------------------------------------------------------------ *)

(** Live current price: in-process top-of-book when sane (within +/-30% of
    the last bar close), else the close itself. Zero network. *)
let live_buy_anchor ~(exchange : string) ~(symbol : string) ~(fallback : float) =
  let band = 0.30 in
  let sane price =
    fallback > 0.0 && price > 0.0 && Float.abs (price -. fallback) /. fallback <= band
  in
  match Exchange.Registry.get exchange with
  | None -> fallback
  | Some (module Ex) ->
    (match Ex.get_top_of_book ~symbol with
     | Some (bid, _, _, _) when sane bid -> bid
     | Some (_, _, ask, _) when sane ask -> ask
     | _ -> fallback)
;;

(** Base/quote parts of a "BASE/QUOTE" symbol (whole string when no slash). *)
let split_symbol (symbol : string) : string * string =
  match String.index_opt symbol '/' with
  | None -> symbol, "USD"
  | Some i ->
    String.sub symbol 0 i, String.sub symbol (i + 1) (String.length symbol - i - 1)
;;

(** Quote tied in resting buys for one asset: fold of the in-process open
    order registry (remaining qty x limit price). Zero network. *)
let committed_buy_value ~(exchange : string) ~(symbol : string) : float =
  match Exchange.Registry.get exchange with
  | None -> 0.0
  | Some (module Ex) ->
    Ex.fold_open_orders ~symbol ~init:0.0 ~f:(fun acc (o : Exchange.Types.open_order) ->
      if o.side = Exchange.Types.Buy && o.remaining_qty > 0.0
      then
        acc
        +. (o.remaining_qty
            *.
            match o.limit_price with
            | Some p -> p
            | None -> 0.0)
      else acc)
;;

(** Whether one asset currently has a resting buy order on exchange. Zero network. *)
let has_resting_buy ~(exchange : string) ~(symbol : string) : bool =
  match Exchange.Registry.get exchange with
  | None -> false
  | Some (module Ex) ->
    Ex.fold_open_orders ~symbol ~init:false ~f:(fun acc (o : Exchange.Types.open_order) ->
      acc || (o.side = Exchange.Types.Buy && o.remaining_qty > 0.0))
;;

(** Base tied in resting sells for one asset (remaining qty sum). *)
let resting_sell_base ~(exchange : string) ~(symbol : string) : float =
  match Exchange.Registry.get exchange with
  | None -> 0.0
  | Some (module Ex) ->
    Ex.fold_open_orders ~symbol ~init:0.0 ~f:(fun acc (o : Exchange.Types.open_order) ->
      if o.side = Exchange.Types.Sell && o.remaining_qty > 0.0
      then acc +. o.remaining_qty
      else acc)
;;

(* ------------------------------------------------------------------ *)
(* Pool events (fills / cancels move availability in process)          *)
(* ------------------------------------------------------------------ *)

type pool_event =
  { pe_account : string (** Account key. *)
  ; pe_delta_quote : float
  ; pe_delta_base : float
  ; pe_base_asset : string
  ; pe_cause : string
  ; pe_baseline : int (** Balance epoch the delta was measured against. *)
  }

let event_mutex = Mutex.create ()
let event_queue_cap = 16_384
let event_queue : pool_event Queue.t = Queue.create ()
let pending_pool_adjustments : (string, pool_event list) Hashtbl.t = Hashtbl.create 8
let balance_epoch : int Atomic.t = Atomic.make 0

let account_key_of ~(exchange : string) ~(testnet : bool) ~(quote : string) : string =
  Printf.sprintf "%s|%s|%s" exchange (string_of_bool testnet) quote
;;

let enqueue_pool_event account ~delta_quote ~delta_base ~base_asset cause =
  Mutex.lock event_mutex;
  if Queue.length event_queue >= event_queue_cap
  then (
    Logging.warn_f ~section "pool event queue full; dropping oldest events";
    Queue.clear event_queue);
  Queue.push
    { pe_account = account
    ; pe_delta_quote = delta_quote
    ; pe_delta_base = delta_base
    ; pe_base_asset = base_asset
    ; pe_cause = cause
    ; pe_baseline = Atomic.get balance_epoch
    }
    event_queue;
  Mutex.unlock event_mutex
;;

(** Moves queued events into the per-account pending adjustment table.
    Called at the top of every pass - the pass itself stays lock-free. *)
let drain_pool_events () =
  Mutex.lock event_mutex;
  let events = Queue.fold (fun acc e -> e :: acc) [] event_queue in
  Queue.clear event_queue;
  Mutex.unlock event_mutex;
  List.iter
    (fun e ->
       let l =
         Hashtbl.find_opt pending_pool_adjustments e.pe_account
         |> Option.value ~default:[]
       in
       Hashtbl.replace pending_pool_adjustments e.pe_account (e :: l))
    (List.rev events)
;;

(** A fill returns/consumes quote AND base: a buy consumes value+fee of
    quote and credits filled base; a sell credits value-fee and debits the
    sold base. Wakes the runtime - deltas are applied in process, so the
    decision never waits on a network balance refresh. *)
let notify_fill
      ~(exchange : string)
      ~(symbol : string)
      ~(testnet : bool)
      ~(side : Exchange.Types.order_side)
      ~(filled_qty : float)
      ~(avg_price : float)
      ~(fee : float)
  =
  let base, quote = split_symbol symbol in
  let value = filled_qty *. avg_price in
  let dq, db =
    match side with
    | Exchange.Types.Buy -> -.(value +. Float.max 0.0 fee), filled_qty
    | Exchange.Types.Sell -> value -. Float.max 0.0 fee, -.filled_qty
  in
  enqueue_pool_event
    (account_key_of ~exchange ~testnet ~quote)
    ~delta_quote:dq
    ~delta_base:db
    ~base_asset:base
    "fill";
  request_pass ()
;;

(** A canceled/rejected/expired order releases committed capital: a canceled
    BUY returns its remaining committed value (remaining_qty x limit price);
    a canceled sell releases base inventory, never quote. Wakes the runtime. *)
let notify_order_cancel
      ~(exchange : string)
      ~(symbol : string)
      ~(testnet : bool)
      ~(side : Exchange.Types.order_side)
      ~(value : float)
  =
  let base, quote = split_symbol symbol in
  if side = Exchange.Types.Buy
  then
    enqueue_pool_event
      (account_key_of ~exchange ~testnet ~quote)
      ~delta_quote:(Float.max 0.0 value)
      ~delta_base:0.0
      ~base_asset:base
      "order_cancel";
  request_pass ()
;;

(** Pending quote/base deltas valid for [epoch]: measured at the current
    balance epoch (a fresher authoritative snapshot already includes them -
    older deltas are dropped, never double-counted). *)
let pending_deltas account epoch =
  match Hashtbl.find_opt pending_pool_adjustments account with
  | None -> 0.0, []
  | Some events ->
    let kept, dq =
      List.fold_left
        (fun (kept, dq) (e : pool_event) ->
           if e.pe_baseline = epoch then e :: kept, dq +. e.pe_delta_quote else kept, dq)
        ([], 0.0)
        events
    in
    dq, kept
;;

let prune_pending account epoch =
  match Hashtbl.find_opt pending_pool_adjustments account with
  | None -> ()
  | Some events ->
    let kept = List.filter (fun (e : pool_event) -> e.pe_baseline = epoch) events in
    if kept = []
    then Hashtbl.remove pending_pool_adjustments account
    else Hashtbl.replace pending_pool_adjustments account kept
;;

(* ------------------------------------------------------------------ *)
(* Venue pools                                                        *)
(* ------------------------------------------------------------------ *)

(** A venue account: pools never cross these. *)
type account =
  { a_exchange : string
  ; a_testnet : bool
  ; a_quote : string
  }

let account_id (a : account) =
  account_key_of ~exchange:a.a_exchange ~testnet:a.a_testnet ~quote:a.a_quote
;;

let account_of_task (t : Oracle_tasks.task) : account =
  let _, quote = split_symbol t.symbol in
  { a_exchange = t.exchange; a_testnet = t.config.testnet; a_quote = quote }
;;

let same_account x y =
  String.equal x.a_exchange y.a_exchange
  && x.a_testnet = y.a_testnet
  && String.equal x.a_quote y.a_quote
;;

(** Tasks grouped by venue account, preserving config.json order (priority
    order within each account). *)
let group_by_account (tasks : Oracle_tasks.task list)
  : (account * Oracle_tasks.task list) list
  =
  let accounts = ref [] in
  List.iter
    (fun (task : Oracle_tasks.task) ->
       let account = account_of_task task in
       if not (List.exists (same_account account) !accounts)
       then accounts := account :: !accounts)
    tasks;
  let accounts = List.rev !accounts in
  List.map
    (fun account ->
       ( account
       , List.filter
           (fun (task : Oracle_tasks.task) -> same_account account (account_of_task task))
           tasks ))
    accounts
;;

(** Last known balance snapshots per account id, warmed by the background
    refresher and the initial pass. *)
type pool_state =
  { snap : Oracle_balances.snapshot
  ; ps_epoch : int
  ; fetched_at : float
  }

let pool_cache : (string, pool_state) Hashtbl.t = Hashtbl.create 8
let clear_pool_cache () = Hashtbl.reset pool_cache

(** Fetch balances for one task (live store first, REST fallback) into the
    pool cache. Network - called from the refresher and startup only. *)
let refresh_balance_of_task (task : Oracle_tasks.task) : unit Lwt.t =
  let account = account_of_task task in
  let id = account_id account in
  Lwt.catch
    (fun () ->
       Oracle_balances.fetch_task_live task
       >|= function
       | Error error ->
         Logging.debug
           ~section
           (Printf.sprintf "balance refresh failed for %s: %s" id error)
       | Ok snapshot ->
         Atomic.incr balance_epoch;
         Hashtbl.replace
           pool_cache
           id
           { snap = snapshot
           ; ps_epoch = Atomic.get balance_epoch
           ; fetched_at = Unix.gettimeofday ()
           })
    (fun exn ->
       Logging.debug
         ~section
         (Printf.sprintf "balance refresh failed for %s: %s" id (Printexc.to_string exn));
       Lwt.return ())
;;

(** Available quote for an account RIGHT NOW: live store when present,
    else the cached snapshot; plus in-process pending deltas measured at the
    snapshot's epoch. Zero network. *)
let available_quote_now (a : account) : float option =
  let id = account_id a in
  let snap_opt =
    match
      Oracle_balances.snapshot_of_live_store
        ~exchange:a.a_exchange
        ~testnet:a.a_testnet
        ()
    with
    | Some snap -> Some snap
    | None -> Option.map (fun p -> p.snap) (Hashtbl.find_opt pool_cache id)
  in
  match snap_opt with
  | None -> None
  | Some snap ->
    let epoch =
      match Hashtbl.find_opt pool_cache id with
      | Some p
        when Option.is_none
               (Oracle_balances.snapshot_of_live_store
                  ~exchange:a.a_exchange
                  ~testnet:a.a_testnet
                  ()) -> p.ps_epoch
      | _ -> Atomic.get balance_epoch
    in
    let dq, pending = pending_deltas id epoch in
    if pending <> [] then prune_pending id epoch;
    Some (Float.max 0.0 (Oracle_balances.available_quote snap ~quote:a.a_quote +. dq))
;;

(** Available base for one symbol right now (same sources), minus nothing:
    reserved_base is excluded upstream by the execution layer's
    available_trading_balance. Resting sells are subtracted separately via
    the open-order registry. Zero network. *)
let available_base_now (a : account) ~(symbol : string) : float option =
  let id = account_id a in
  let snap_opt =
    match
      Oracle_balances.snapshot_of_live_store
        ~exchange:a.a_exchange
        ~testnet:a.a_testnet
        ()
    with
    | Some snap -> Some snap
    | None -> Option.map (fun p -> p.snap) (Hashtbl.find_opt pool_cache id)
  in
  match snap_opt with
  | None -> None
  | Some snap ->
    let base, _ = split_symbol symbol in
    let epoch =
      match Hashtbl.find_opt pool_cache id with
      | Some p
        when Option.is_none
               (Oracle_balances.snapshot_of_live_store
                  ~exchange:a.a_exchange
                  ~testnet:a.a_testnet
                  ()) -> p.ps_epoch
      | _ -> Atomic.get balance_epoch
    in
    let _, pending = pending_deltas id epoch in
    let db =
      List.fold_left
        (fun acc (e : pool_event) ->
           if String.equal e.pe_base_asset base then acc +. e.pe_delta_base else acc)
        0.0
        pending
    in
    if pending <> [] then prune_pending id epoch;
    Some (Float.max 0.0 (Oracle_balances.available_asset snap ~asset:base +. db))
;;

(* ------------------------------------------------------------------ *)
(* Fees (hot path: pure lookups only)                                 *)
(* ------------------------------------------------------------------ *)

(** Maker fee for one asset without network: explicit config value, else the
    fee cache warmed by the refresher, else the venue's registered default. *)
let fees_now (t : Oracle_tasks.task) : Oracle_core.fee_model =
  let maker =
    match t.config.maker_fee with
    | Some f -> f
    | None ->
      (match Hashtbl.find_opt Oracle_fees.fee_cache (t.exchange, t.symbol) with
       | Some (m, _) -> m
       | None -> fst (Oracle_fees.venue_default_fees t.exchange t.symbol))
  in
  { Oracle_core.maker_fee = Float.max 0.0 maker; fee_in_base_buy = false }
;;

(* ------------------------------------------------------------------ *)
(* The pass                                                           *)
(* ------------------------------------------------------------------ *)

let string_of_regime = function
  | Oracle_core.Normal -> "normal"
  | Oracle_core.Floor_extension -> "floor extension"
  | Oracle_core.Unprecedented_lows -> "unprecedented lows"
;;

let string_of_branch = function
  | Oracle_core.Reachable -> "reachable"
  | Oracle_core.Surplus -> "surplus"
  | Oracle_core.Unreachable -> "unreachable"
;;

(** One venue re-resolve: walk the account's strategies in config order,
    size each against the entire remaining pool, deduct each funded need,
    and fire the cancellation cascade for starved strategies. *)
let run_account_pass
      ~(config : runtime_config)
      ~(account : account)
      ~(tasks : Oracle_tasks.task list)
  : decision list Lwt.t
  =
  match available_quote_now account with
  | None ->
    Logging.warn_f
      ~section
      "no balance data for %s yet; keeping last-known-good decisions"
      (account_id account);
    (* Keep prior decisions for this venue unchanged. *)
    Lwt.return
      (List.filter
         (fun (d : decision) ->
            List.exists
              (fun (t : Oracle_tasks.task) ->
                 String.equal t.exchange d.exchange && String.equal t.symbol d.symbol)
              tasks)
         (decisions ()))
  | Some pool ->
    let committed_venue_buys =
      List.fold_left
        (fun acc (t : Oracle_tasks.task) ->
           acc +. committed_buy_value ~exchange:t.exchange ~symbol:t.symbol)
        0.0
        tasks
    in
    let total_venue_quote = pool +. committed_venue_buys in
    let remaining = ref pool in
    let built
      : (Oracle_tasks.task * decision * float * float * Oracle_pipeline.outcome option) list ref
      =
      ref []
    in
    List.iteri
      (fun _idx (t : Oracle_tasks.task) ->
         let t_asset = Mtime_clock.now_ns () in
         let target_survival, min_active_dsurv, qty_cap_mult =
           effective_knobs ~config ~symbol:t.symbol
         in
         let qty_raw = float_of_string_opt t.config.qty |> Option.value ~default:0.0 in
         let bounds =
           { Oracle_core.qty = Float.max 1e-12 qty_raw
           ; qty_cap_mult = Float.max 1.0 qty_cap_mult
           ; gi_min = fst t.config.grid_interval
           ; gi_max = snd t.config.grid_interval
           }
         in
         (* No usable data yet: publish NOTHING for this asset rather than a
            garbage-zero inactive decision - a fabricated decision would open
            the domain's startup gate on values that were never computed.
            The asset joins the surface on the next pass, once the
            background refresh has delivered its history and balances. *)
         let skip_asset reason =
           record_asset_latency t.symbol (span_from t_asset) (fun () -> reason);
           Logging.debug_f
             ~section
             "%s/%s: %s; no decision published this pass"
             t.exchange
             t.symbol
             reason
         in
         match Hashtbl.find_opt history_cache (t.exchange, t.symbol) with
         | None -> skip_asset "history unavailable"
         | Some series ->
           let fallback_close =
             Option.value (Oracle_pipeline.current_price_of_series series) ~default:0.0
           in
           if fallback_close <= 0.0
           then skip_asset "history has no usable close"
           else (
             let current =
               live_buy_anchor
                 ~exchange:t.exchange
                 ~symbol:t.symbol
                 ~fallback:fallback_close
             in
             let resting_buy = has_resting_buy ~exchange:t.exchange ~symbol:t.symbol in
             let committed_buy =
               committed_buy_value ~exchange:t.exchange ~symbol:t.symbol
             in
             let effective_quote =
               if resting_buy then !remaining +. committed_buy else !remaining
             in
             let inputs : Oracle_pipeline.inputs =
               { exchange = t.exchange
               ; symbol = t.symbol
               ; bars = series.bars
               ; current_price = current
               ; available_quote = effective_quote
               ; sell_qty = 0.0
               ; bounds
               ; target_survival
               ; min_active_dsurv
               ; fees = fees_now t
               ; has_resting_buy = resting_buy
               }
             in
             match Oracle_pipeline.decide ~inputs with
             | None -> skip_asset "references unavailable"
             | Some o ->
               let base_avail =
                 Option.value (available_base_now account ~symbol:t.symbol) ~default:0.0
               in
               let sell_qty =
                 Oracle_pools.sell_qty_of
                   ~base_balance:base_avail
                   ~reserved_base:0.0
                   ~resting_sell_base:
                     (resting_sell_base ~exchange:t.exchange ~symbol:t.symbol)
               in
               let reason =
                 if o.decision.active
                 then ""
                 else if o.resolution.d_surv < min_active_dsurv
                 then
                   Printf.sprintf
                     "d_surv %.3f below min_active_dsurv %.3f"
                     o.resolution.d_surv
                     min_active_dsurv
                 else "awaiting reactivation: quote does not cover buy"
               in
               let d : decision =
                 { exchange = t.exchange
                 ; symbol = t.symbol
                 ; active = o.decision.active
                 ; grid_interval = o.decision.grid_interval
                 ; buy_qty = o.decision.buy_qty
                 ; sell_qty
                 ; max_drawdown_pct = o.refs.max_drawdown_pct
                 ; reason
                 ; d_surv = o.resolution.d_surv
                 ; regime = string_of_regime o.runway.regime
                 ; branch = string_of_branch o.resolution.branch
                 ; cancel_resting_buys = false
                 ; updated_at = Unix.gettimeofday ()
                 }
               in
               record_asset_latency
                 t.symbol
                 (span_from t_asset)
                 (fun () -> if d.active then "active" else "inactive");
               let need = d.buy_qty *. current in
               (* Funded strategies tie their next buy's quote; starved ones
                  pass capacity down untouched. Resting buys are already committed
                  in the venue pool, so only fresh active placements consume free quote. *)
               if d.active && (not resting_buy) && need <= !remaining +. 1e-9
               then remaining := !remaining -. need;
               built := (t, d, need, current, Some o) :: !built))
      tasks;
     let built_rev = List.rev !built in
     let key_of_task (t : Oracle_tasks.task) =
       Printf.sprintf "%s|%s" t.exchange t.symbol
     in
     let global_index (lt : Oracle_tasks.task) =
       let rec pos (k : int) (l : Oracle_tasks.task list) : int =
         match l with
         | [] -> k
         | x :: r ->
           if String.equal x.symbol lt.symbol && String.equal x.exchange lt.exchange
           then k
           else pos (k + 1) r
       in
       pos 0 tasks
     in
     (* Shared venue drawdown simulation: active strategies execute 1 order
        sequentially in priority order until venue quote capital is exhausted. *)
     let active_sim : Oracle_pools.sim_strategy list =
       List.filter_map
         (fun ((t, d, _, current, _) :
                 Oracle_tasks.task * decision * float * float * Oracle_pipeline.outcome option) ->
            if d.active
            then
              Some
                { Oracle_pools.id = key_of_task t
                ; priority = global_index t
                ; current
                ; grid_interval = d.grid_interval
                ; buy_qty = d.buy_qty
                ; maker_fee = (fees_now t).maker_fee
                }
            else None)
         built_rev
     in
     let sim_dsurvs =
       Oracle_pools.simulate_drawdown_survival ~total_quote:total_venue_quote active_sim
     in
     let built_rev =
       List.map
         (fun ((t, d, need, current, outcome) :
                 Oracle_tasks.task * decision * float * float * Oracle_pipeline.outcome option) ->
            let d_surv =
              if d.active
              then
                Option.value (List.assoc_opt (key_of_task t) sim_dsurvs) ~default:0.0
              else 0.0
            in
            (t, { d with d_surv }, need, current, outcome))
         built_rev
     in
     (* Cancellation cascade: a starved strategy (sizing met the survival
        requirement but its next buy does not fit) cancels lower-priority
        resting buys until its need fits - many lesser orders may be
        cancelled to satisfy one greater. The trigger's own orders are never
        cancelled. If no combination fits, resolution proceeds to the
        next-highest priority: nothing is flagged and capacity stays with the
        strategies that own it. Cancelled strategies re-evaluate on the
        cancel event this very pass triggers, resuming iff quote covers their
        buy. *)
     let rec drop n = function
       | [] -> []
       | _ :: r -> if n = 0 then r else drop (n - 1) r
     in
     let flagged : string list ref = ref [] in
     List.iteri
       (fun i
         ((t, d, need, _current, outcome) :
           Oracle_tasks.task * decision * float * float * Oracle_pipeline.outcome option) ->
          match outcome with
          | None -> ()
          | Some _ when d.active -> ()
          | Some o ->
            let eff_target_survival, _, _ =
              effective_knobs ~config ~symbol:t.symbol
            in
            if not (o.resolution.d_surv >= eff_target_survival)
            then ()
            else (
              let lower = drop (i + 1) tasks in
              let claims =
                lower
                |> List.filter (fun (lt : Oracle_tasks.task) ->
                  committed_buy_value ~exchange:lt.exchange ~symbol:lt.symbol > 0.0)
                |> List.map (fun (lt : Oracle_tasks.task) ->
                  (* Global config index: higher index = lower seniority, so
                     descending sort cancels the least senior first. *)
                  { Oracle_pools.id = key_of_task lt
                  ; priority = global_index lt
                  ; need_quote = 0.0
                  ; resting_buy_quote =
                      committed_buy_value ~exchange:lt.exchange ~symbol:lt.symbol
                  })
              in
              let plan =
                Oracle_pools.cascade
                  ~available:!remaining
                  ~need
                  ~trigger_id:(key_of_task t)
                  ~claims
              in
              if plan <> []
              then (
                flagged := List.rev_append plan !flagged;
                Logging.info_f
                  ~section
                  "cancellation cascade for %s/%s (need $%.2f vs $%.2f available): \
                   cancelling resting buys of [%s]"
                  t.exchange
                  t.symbol
                  need
                  !remaining
                  (String.concat ", " plan);
                ())
              else ()))
       built_rev;
     Lwt.return
       (List.map
          (fun ((_, d, _, _, _) :
                 Oracle_tasks.task * decision * float * float * Oracle_pipeline.outcome option) ->
             if List.mem (Printf.sprintf "%s|%s" d.exchange d.symbol) !flagged
             then { d with cancel_resting_buys = true }
             else d)
          built_rev)
;;

(** One full re-resolve across all venues. *)
let run_pass
      ~(config : runtime_config)
      ~(tasks : Oracle_tasks.task list)
      ~(on_publish : string list -> decision list -> unit)
  : unit Lwt.t
  =
  let started = Mtime_clock.now_ns () in
  let groups = group_by_account tasks in
  Lwt_list.fold_left_s
    (fun acc (account, tsks) ->
       run_account_pass ~config ~account ~tasks:tsks >|= fun ds -> ds :: acc)
    []
    groups
  >>= fun decision_lists ->
  publish ~on_publish (List.concat (List.rev decision_lists));
  Atomic.incr pass_count;
  let pass_span = span_from started in
  Latency_profiler.record (Lazy.force engine_profs).prof_pass pass_span;
  let _ = Latency_profiler.snapshot_and_reset (Lazy.force engine_profs).prof_pass in
  List.iter
    (fun (t : Oracle_tasks.task) ->
       ignore (Latency_profiler.snapshot_and_reset (asset_profiler_of t.symbol)))
    tasks;
  Logging.debug_f
    ~section
    "pass %d done (%d assets, %.1fms)"
    (Atomic.get pass_count)
    (List.length tasks)
    (Mtime.Span.to_float_ns pass_span /. 1e9 *. 1000.0);
  Lwt.return ()
;;

(* ------------------------------------------------------------------ *)
(* Background refresh                                                 *)
(* ------------------------------------------------------------------ *)

(** Refreshes histories + balances for every task once (network). Sets
    [materialized] after the first attempt and wakes the runtime when any
    history changed or balances arrived. *)
let refresh_once ~(offline : bool) ~(tasks : Oracle_tasks.task list) : unit Lwt.t =
  let started = Mtime_clock.now_ns () in
  Lwt_list.iter_s
    (fun (t : Oracle_tasks.task) ->
       refresh_asset_history ~offline ~exchange:t.exchange ~symbol:t.symbol
       >>= fun changed ->
       if changed then Atomic.set history_changed true;
       Lwt.return ())
    tasks
  >>= fun () ->
  let t_bal = Mtime_clock.now_ns () in
  let accounts = group_by_account tasks |> List.map fst in
  Lwt_list.iter_s
    (fun account ->
       match
         List.find_opt
           (fun (t : Oracle_tasks.task) -> same_account account (account_of_task t))
           tasks
       with
       | None -> Lwt.return ()
       | Some task -> refresh_balance_of_task task)
    accounts
  >>= fun () ->
  Latency_profiler.record (Lazy.force engine_profs).prof_balance (span_from t_bal);
  Atomic.incr refresh_generation;
  Atomic.set materialized_ref (Some { m_epoch = Atomic.get refresh_generation });
  Latency_profiler.record (Lazy.force engine_profs).prof_fetch (span_from started);
  let _ = Latency_profiler.snapshot_and_reset (Lazy.force engine_profs).prof_balance in
  let _ = Latency_profiler.snapshot_and_reset (Lazy.force engine_profs).prof_fetch in
  request_pass ();
  Lwt.return ()
;;

let rec refresh_loop
          ~(offline : bool)
          ~(config : runtime_config)
          ~(tasks : Oracle_tasks.task list)
  : unit Lwt.t
  =
  if is_stopped ()
  then Lwt.return ()
  else
    refresh_once ~offline ~tasks
    >>= fun () ->
    wait_until
      ~deadline:(Unix.gettimeofday () +. config.refresh_seconds)
      ~generation:(Atomic.get pass_requested)
      ()
    >>= fun () -> refresh_loop ~offline ~config ~tasks
;;

(* ------------------------------------------------------------------ *)
(* Main loop                                                          *)
(* ------------------------------------------------------------------ *)

(** Runs the oracle until shutdown: initial background refresh, then a
    wake-driven pass loop. Events (fills, cancels, balance changes,
    [request_pass]) coalesce into single re-resolves; the refresh cadence is
    the fallback poll. Returns when [shutdown] is requested. *)
let run_loop
      ~(config : runtime_config)
      ~(trading : Dio_strategies.Strategy_common.trading_config list)
      ~(on_publish : string list -> decision list -> unit)
      ()
  : unit Lwt.t
  =
  let tasks, unsupported =
    Oracle_tasks.resolve_tasks
      ~symbol:""
      ~exchange:""
      ~exchange_explicit:false
      ~trading
      ~offline:false
  in
  List.iter
    (fun (sym, exch) ->
       Logging.warn_f
         ~section
         "%s/%s has no capital-survival adapter; it will receive no decisions"
         exch
         sym)
    unsupported;
  (* Warm fees and histories in the background; assets without usable data
     simply receive no decision until the first refresh lands (domains keep
     their startup gate closed - they place nothing before real values). *)
  Lwt.async (fun () ->
    Lwt_list.iter_s
      (fun (t : Oracle_tasks.task) ->
         if Option.is_none t.config.maker_fee
         then
           Lwt.catch
             (fun () ->
                Oracle_fees.resolved_fees
                  ~exchange:t.exchange
                  ~symbol:t.symbol
                  ~testnet:t.config.testnet
                >|= fun _ -> ())
             (fun _ -> Lwt.return ())
         else Lwt.return ())
      tasks
    >>= fun () -> refresh_loop ~offline:false ~config ~tasks);
  let rec loop () =
    if is_stopped ()
    then (
      Logging.info ~section "oracle runtime stopped";
      Lwt.return ())
    else
      run_pass ~config ~tasks ~on_publish
      >>= fun () ->
      wait_until
        ~deadline:(Unix.gettimeofday () +. (Float.max 1.0 config.refresh_seconds /. 4.0))
        ~generation:(Atomic.get pass_requested)
        ()
      >>= loop
  in
  loop ()
;;
