(test
 (name test_event_bus)
 (libraries dio.concurrency alcotest))

(test
 (name test_concurrency_primitives)
 (libraries dio.concurrency alcotest))

(test
 (name test_cow_table)
 (libraries dio.concurrency alcotest))

(test
 (name test_id_table)
 (libraries dio.concurrency alcotest))

(test
 (name test_fifo_index)
 (libraries dio.concurrency alcotest))
